#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🚀🚀🚀Styling, testing and building your project before committing'

# Check pritter standards
cd ./frontend pnpm run check-format || 
(
    echo '🤮🤮🤮Its forking raw - Your styling looks disgusting. 
        Prettier check failed. yarn format or pnpm run format, add changes and try commit again';
    false;
)
echo '😍GREAT! you have successfully passed the prettier standards'

# Check tsconfig standards
pnpm run check-types ||
(
    echo '☠️☠️☠️failed type check.
        Are you seriously trying to write that ? make the change required above'
    false;
)
echo '😍PERFECT! keep like that!'

# Check ESLint Standards
pnpm run lint || 
(
    echo '☠️☠️☠️Get that weak shit out of here! Eslint check failed. make the required changes listed above, add change and try to commit again'
    false; 
)
echo '😍EXCELENT! and yes you made it through again'
echo '😍Finnaly! you publishing this code🚀'
echo '😍😍😍you win this time rizal... I am committing this now and please check your changes'
