import type { Metadata } from 'next';
import '../styles/globals.scss';
import { inter } from '@/ui/fonts';
import Swiper from 'swiper';
import 'swiper/css/bundle';

export const metadata: Metadata = {
  title: 'RZ-Dev | E-Learning',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
